export const REGIONS = [
  { id: 'Abruzzo', value: 'regions.abruzzo' },
  { id: 'Basilicata', value: 'regions.basilicata' },
  { id: 'Calabria', value: 'regions.calabria' },
  { id: 'Campania', value: 'regions.campania' },
  { id: 'Emilia-Romagna', value: 'regions.emilia-romagna' },
  { id: 'Friuli-Venezia Giulia', value: 'regions.friuli-venezia-giulia' },
  { id: 'Lazio', value: 'regions.lazio' },
  { id: 'Liguria', value: 'regions.liguria' },
  { id: 'Lombardia', value: 'regions.lombardia' },
  { id: 'Marche', value: 'regions.marche' },
  { id: 'Molise', value: 'regions.molise' },
  { id: 'Piemonte', value: 'regions.piemonte' },
  { id: 'Puglia', value: 'regions.puglia' },
  { id: 'Sardegna', value: 'regions.sardegna' },
  { id: 'Sicilia', value: 'regions.sicilia' },
  { id: 'Toscana', value: 'regions.toscana' },
  { id: 'Trentino-Alto Adige', value: 'regions.trentino-alto-adige' },
  { id: 'Umbria', value: 'regions.umbria' },
  { id: "Valle d'Aosta", value: 'regions.valle-d-aosta' },
  { id: 'Veneto', value: 'regions.veneto' },
 ] as const

