export const regions = {
  'Abruzzo': 'regions.abruzzo',
  'Basilicata': 'regions.basilicata',
  'Calabria': 'regions.calabria',
  'Campania': 'regions.campania',
  'Emilia-Romagna': 'regions.emilia-romagna',
  'Friuli-Venezia Giulia':  'regions.friuli-venezia-giulia',
  'Lazio': 'regions.lazio',
  'Liguria': 'regions.liguria',
  'Lombardia': 'regions.lombardia',
  'Marche': 'regions.marche',
  'Molise': 'regions.molise',
  'Piemonte': 'regions.piemonte',
  'Puglia': 'regions.puglia',
  'Sardegna': 'regions.sardegna',
  'Sicilia': 'regions.sicilia',
  'Toscana': 'regions.toscana',
  'Trentino-Alto Adige': 'regions.trentino-alto-adige',
  'Umbria': 'regions.umbria',
  "Valle d'Aosta": 'regions.valle-d-aosta',
  'Veneto': 'regions.veneto',
} as const

