/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExternalIndexRouteImport } from './routes/external/index'
import { Route as HerbariaIdIndexRouteImport } from './routes/$herbariaId/index'
import { Route as HerbariaIdSearchRouteRouteImport } from './routes/$herbariaId/search/route'
import { Route as HerbariaIdSearchIndexRouteImport } from './routes/$herbariaId/search/index'
import { Route as HerbariaIdSpecimensOccurrenceIDRouteImport } from './routes/$herbariaId/specimens/$occurrenceID'
import { Route as HerbariaIdSearchTableRouteImport } from './routes/$herbariaId/search/table'
import { Route as HerbariaIdSearchMapRouteImport } from './routes/$herbariaId/search/map'
import { Route as HerbariaIdSearchGraphsRouteImport } from './routes/$herbariaId/search/graphs'
import { Route as HerbariaIdSearchDebugFiltersRouteImport } from './routes/$herbariaId/search/debug-filters'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalIndexRoute = ExternalIndexRouteImport.update({
  id: '/external/',
  path: '/external/',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbariaIdIndexRoute = HerbariaIdIndexRouteImport.update({
  id: '/$herbariaId/',
  path: '/$herbariaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbariaIdSearchRouteRoute = HerbariaIdSearchRouteRouteImport.update({
  id: '/$herbariaId/search',
  path: '/$herbariaId/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbariaIdSearchIndexRoute = HerbariaIdSearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HerbariaIdSearchRouteRoute,
} as any)
const HerbariaIdSpecimensOccurrenceIDRoute =
  HerbariaIdSpecimensOccurrenceIDRouteImport.update({
    id: '/$herbariaId/specimens/$occurrenceID',
    path: '/$herbariaId/specimens/$occurrenceID',
    getParentRoute: () => rootRouteImport,
  } as any)
const HerbariaIdSearchTableRoute = HerbariaIdSearchTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => HerbariaIdSearchRouteRoute,
} as any)
const HerbariaIdSearchMapRoute = HerbariaIdSearchMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => HerbariaIdSearchRouteRoute,
} as any)
const HerbariaIdSearchGraphsRoute = HerbariaIdSearchGraphsRouteImport.update({
  id: '/graphs',
  path: '/graphs',
  getParentRoute: () => HerbariaIdSearchRouteRoute,
} as any)
const HerbariaIdSearchDebugFiltersRoute =
  HerbariaIdSearchDebugFiltersRouteImport.update({
    id: '/debug-filters',
    path: '/debug-filters',
    getParentRoute: () => HerbariaIdSearchRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/$herbariaId/search': typeof HerbariaIdSearchRouteRouteWithChildren
  '/$herbariaId': typeof HerbariaIdIndexRoute
  '/external': typeof ExternalIndexRoute
  '/$herbariaId/search/debug-filters': typeof HerbariaIdSearchDebugFiltersRoute
  '/$herbariaId/search/graphs': typeof HerbariaIdSearchGraphsRoute
  '/$herbariaId/search/map': typeof HerbariaIdSearchMapRoute
  '/$herbariaId/search/table': typeof HerbariaIdSearchTableRoute
  '/$herbariaId/specimens/$occurrenceID': typeof HerbariaIdSpecimensOccurrenceIDRoute
  '/$herbariaId/search/': typeof HerbariaIdSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/$herbariaId': typeof HerbariaIdIndexRoute
  '/external': typeof ExternalIndexRoute
  '/$herbariaId/search/debug-filters': typeof HerbariaIdSearchDebugFiltersRoute
  '/$herbariaId/search/graphs': typeof HerbariaIdSearchGraphsRoute
  '/$herbariaId/search/map': typeof HerbariaIdSearchMapRoute
  '/$herbariaId/search/table': typeof HerbariaIdSearchTableRoute
  '/$herbariaId/specimens/$occurrenceID': typeof HerbariaIdSpecimensOccurrenceIDRoute
  '/$herbariaId/search': typeof HerbariaIdSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/$herbariaId/search': typeof HerbariaIdSearchRouteRouteWithChildren
  '/$herbariaId/': typeof HerbariaIdIndexRoute
  '/external/': typeof ExternalIndexRoute
  '/$herbariaId/search/debug-filters': typeof HerbariaIdSearchDebugFiltersRoute
  '/$herbariaId/search/graphs': typeof HerbariaIdSearchGraphsRoute
  '/$herbariaId/search/map': typeof HerbariaIdSearchMapRoute
  '/$herbariaId/search/table': typeof HerbariaIdSearchTableRoute
  '/$herbariaId/specimens/$occurrenceID': typeof HerbariaIdSpecimensOccurrenceIDRoute
  '/$herbariaId/search/': typeof HerbariaIdSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/$herbariaId/search'
    | '/$herbariaId'
    | '/external'
    | '/$herbariaId/search/debug-filters'
    | '/$herbariaId/search/graphs'
    | '/$herbariaId/search/map'
    | '/$herbariaId/search/table'
    | '/$herbariaId/specimens/$occurrenceID'
    | '/$herbariaId/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/$herbariaId'
    | '/external'
    | '/$herbariaId/search/debug-filters'
    | '/$herbariaId/search/graphs'
    | '/$herbariaId/search/map'
    | '/$herbariaId/search/table'
    | '/$herbariaId/specimens/$occurrenceID'
    | '/$herbariaId/search'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/$herbariaId/search'
    | '/$herbariaId/'
    | '/external/'
    | '/$herbariaId/search/debug-filters'
    | '/$herbariaId/search/graphs'
    | '/$herbariaId/search/map'
    | '/$herbariaId/search/table'
    | '/$herbariaId/specimens/$occurrenceID'
    | '/$herbariaId/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  HerbariaIdSearchRouteRoute: typeof HerbariaIdSearchRouteRouteWithChildren
  HerbariaIdIndexRoute: typeof HerbariaIdIndexRoute
  ExternalIndexRoute: typeof ExternalIndexRoute
  HerbariaIdSpecimensOccurrenceIDRoute: typeof HerbariaIdSpecimensOccurrenceIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external/': {
      id: '/external/'
      path: '/external'
      fullPath: '/external'
      preLoaderRoute: typeof ExternalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$herbariaId/': {
      id: '/$herbariaId/'
      path: '/$herbariaId'
      fullPath: '/$herbariaId'
      preLoaderRoute: typeof HerbariaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$herbariaId/search': {
      id: '/$herbariaId/search'
      path: '/$herbariaId/search'
      fullPath: '/$herbariaId/search'
      preLoaderRoute: typeof HerbariaIdSearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$herbariaId/search/': {
      id: '/$herbariaId/search/'
      path: '/'
      fullPath: '/$herbariaId/search/'
      preLoaderRoute: typeof HerbariaIdSearchIndexRouteImport
      parentRoute: typeof HerbariaIdSearchRouteRoute
    }
    '/$herbariaId/specimens/$occurrenceID': {
      id: '/$herbariaId/specimens/$occurrenceID'
      path: '/$herbariaId/specimens/$occurrenceID'
      fullPath: '/$herbariaId/specimens/$occurrenceID'
      preLoaderRoute: typeof HerbariaIdSpecimensOccurrenceIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$herbariaId/search/table': {
      id: '/$herbariaId/search/table'
      path: '/table'
      fullPath: '/$herbariaId/search/table'
      preLoaderRoute: typeof HerbariaIdSearchTableRouteImport
      parentRoute: typeof HerbariaIdSearchRouteRoute
    }
    '/$herbariaId/search/map': {
      id: '/$herbariaId/search/map'
      path: '/map'
      fullPath: '/$herbariaId/search/map'
      preLoaderRoute: typeof HerbariaIdSearchMapRouteImport
      parentRoute: typeof HerbariaIdSearchRouteRoute
    }
    '/$herbariaId/search/graphs': {
      id: '/$herbariaId/search/graphs'
      path: '/graphs'
      fullPath: '/$herbariaId/search/graphs'
      preLoaderRoute: typeof HerbariaIdSearchGraphsRouteImport
      parentRoute: typeof HerbariaIdSearchRouteRoute
    }
    '/$herbariaId/search/debug-filters': {
      id: '/$herbariaId/search/debug-filters'
      path: '/debug-filters'
      fullPath: '/$herbariaId/search/debug-filters'
      preLoaderRoute: typeof HerbariaIdSearchDebugFiltersRouteImport
      parentRoute: typeof HerbariaIdSearchRouteRoute
    }
  }
}

interface HerbariaIdSearchRouteRouteChildren {
  HerbariaIdSearchDebugFiltersRoute: typeof HerbariaIdSearchDebugFiltersRoute
  HerbariaIdSearchGraphsRoute: typeof HerbariaIdSearchGraphsRoute
  HerbariaIdSearchMapRoute: typeof HerbariaIdSearchMapRoute
  HerbariaIdSearchTableRoute: typeof HerbariaIdSearchTableRoute
  HerbariaIdSearchIndexRoute: typeof HerbariaIdSearchIndexRoute
}

const HerbariaIdSearchRouteRouteChildren: HerbariaIdSearchRouteRouteChildren = {
  HerbariaIdSearchDebugFiltersRoute: HerbariaIdSearchDebugFiltersRoute,
  HerbariaIdSearchGraphsRoute: HerbariaIdSearchGraphsRoute,
  HerbariaIdSearchMapRoute: HerbariaIdSearchMapRoute,
  HerbariaIdSearchTableRoute: HerbariaIdSearchTableRoute,
  HerbariaIdSearchIndexRoute: HerbariaIdSearchIndexRoute,
}

const HerbariaIdSearchRouteRouteWithChildren =
  HerbariaIdSearchRouteRoute._addFileChildren(
    HerbariaIdSearchRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  HerbariaIdSearchRouteRoute: HerbariaIdSearchRouteRouteWithChildren,
  HerbariaIdIndexRoute: HerbariaIdIndexRoute,
  ExternalIndexRoute: ExternalIndexRoute,
  HerbariaIdSpecimensOccurrenceIDRoute: HerbariaIdSpecimensOccurrenceIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
